apiVersion: v1
kind: Namespace
metadata:
  name: student-api

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: student-api
type: Opaque
data:
  username: cG9zdGdyZXM=
  password: cG9zdGdyZXM=

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: student-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      nodeSelector:
        type: database
      containers:
        - name: postgres
          image: postgres:16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: students
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: student-api
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
