replicaCount: 1

image:
  repository: shrenikmehar/student-api
  tag: "35549fa8b8cff697d5e976d97525e9aa545a488e"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 8080
  nodePort: 30080

nodeSelector:
  type: application

config:
  dbHost: ""
  dbPort: ""
  dbName: ""

secret:
  dbUser: ""
  dbPassword: ""

vaultToken: ""
