replicaCount: 1

image:
  repository: shrenikmehar/student-api
  tag: "6d15ac0e5ded80a3349754801113f599cc350d50"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 8080
  nodePort: 30080

nodeSelector:
  type: application

config:
  dbHost: ""
  dbPort: ""
  dbName: ""

secret:
  dbUser: ""
  dbPassword: ""

vaultToken: ""
