apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}
data:
  DB_HOST: {{ .Values.config.dbHost }}
  DB_PORT: {{ .Values.config.dbPort }}
  DB_NAME: {{ .Values.config.dbName }}
