services:

  postgres:
    image: postgres:16
    container_name: student-postgres
    environment:
      POSTGRES_DB: students
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api1
      - api2

  api1:
    image: shrenikmehar/student-api:1.0.0
    container_name: student-api-1
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: students
      DB_USER: postgres
      DB_PASSWORD: postgres

  api2:
    image: shrenikmehar/student-api:1.0.0
    container_name: student-api-2
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: students
      DB_USER: postgres
      DB_PASSWORD: postgres

volumes:
  postgres_data:
