replicaCount: 1

image:
  repository: postgres
  tag: "16"
  pullPolicy: IfNotPresent

nodeSelector:
  type: database

auth:
  database: "students"
  username: "postgres"
  password: "postgres"

service:
  port: 5432
